<?php

namespace Database\Factories;

use App\Enums\InvoiceStatus;
use App\Models\Centre;
use App\Models\Invoice;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Invoice>
 */
class InvoiceFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            // number will be auto-generated by Invoice model's boot() method
            'tenant_id' => Tenant::factory(),
            'centre_id' => Centre::factory(),
            'user_id' => User::factory(),
            'date' => fake()->dateTimeBetween('-30 days', 'now'),
            'due_at' => fake()->dateTimeBetween('now', '+30 days'),
            'status' => fake()->randomElement(InvoiceStatus::cases()),
            // Set totals to 0 initially - will be calculated when invoice items are created
            'total_items' => 0,
            'total_discounts' => 0,
            'total_amount' => 0,
            'total' => 0,
        ];
    }

    /**
     * Indicate that the invoice is in draft status.
     */
    public function draft(): Factory
    {
        return $this->state(fn (array $attributes) => [
            'status' => InvoiceStatus::DRAFT,
        ]);
    }

    /**
     * Indicate that the invoice is in pending status.
     */
    public function pending(): Factory
    {
        return $this->state(fn (array $attributes) => [
            'status' => InvoiceStatus::PENDING,
        ]);
    }

    /**
     * Indicate that the invoice is in paid status.
     */
    public function paid(): Factory
    {
        return $this->state(fn (array $attributes) => [
            'status' => InvoiceStatus::PAID,
            'due_at' => fake()->dateTimeBetween('-30 days', 'now'),
        ]);
    }

    /**
     * Indicate that the invoice is in partially paid status.
     */
    public function partiallyPaid(): Factory
    {
        return $this->state(fn (array $attributes) => [
            'status' => InvoiceStatus::PARTIALLY_PAID,
        ]);
    }

    /**
     * Indicate that the invoice is in overdue status.
     */
    public function overdue(): Factory
    {
        return $this->state(fn (array $attributes) => [
            'status' => InvoiceStatus::OVERDUE,
            'due_at' => fake()->dateTimeBetween('-30 days', '-1 day'),
        ]);
    }
}
